package ui;


import client.ChatClient;
import client.MessageHandler;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HELLO
 */
public class MainForm extends javax.swing.JFrame {
    
    private ChatClient chatClient;
    private final  DateTimeFormatter timeFmt = DateTimeFormatter.ofPattern("HH:mm:ss");
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        configureTextArea();
        connectToServer();     
        installEnterToSend();
    }
    
    private void configureTextArea() {
        taMessageDisplay.setEditable(false);
        taMessageDisplay.setLineWrap(true);
        taMessageDisplay.setWrapStyleWord(true);
    }

    private void appendMessage(String sender, String content) {
        String time = LocalTime.now().truncatedTo(ChronoUnit.SECONDS).format(timeFmt);
        String line = String.format("[%s] %s: %s", time, sender, content);
        if (taMessageDisplay.getDocument().getLength() == 0) {
            taMessageDisplay.setText(line);
        } else {
            taMessageDisplay.append("\n" + line);
        }
        taMessageDisplay.setCaretPosition(taMessageDisplay.getDocument().getLength());
    }

    private void installEnterToSend() {
        messageInputField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override public void keyPressed(java.awt.event.KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER && !e.isShiftDown()) {
                    e.consume();
                    sendCurrentText();
                }
            }
        });
    }

    private void connectToServer() {
        chatClient = new ChatClient("127.0.0.1", 5000);
        try {
            chatClient.connect(new MessageHandler() {
                @Override public void onMessage(String msg) {
                    SwingUtilities.invokeLater(() -> appendMessage("Others", msg));
                }
            });
            appendMessage("System", "Connected to server");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cannot connect: " + e.getMessage(),
                    "Connection Error", JOptionPane.ERROR_MESSAGE);
        }

        // đóng socket khi tắt
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override public void windowClosing(java.awt.event.WindowEvent e) {
                if (chatClient != null) chatClient.close();
            }
        });
    }
    
    private void sendCurrentText() {
        final String message = messageInputField.getText().trim();
        if (message.isBlank()) {
            JOptionPane.showMessageDialog(
                this,
                "Please enter message!",
                "Missing content",
                JOptionPane.WARNING_MESSAGE
            );
            messageInputField.requestFocus();
            return;
        }

        try {
            if (chatClient != null) {
                chatClient.sendMessage(message);   // Gửi lên server (server sẽ broadcast)
            }
            appendMessage("Me", message);          // Hiển thị cục bộ
            messageInputField.setText("");
            messageInputField.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Send failed: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taMessageDisplay = new javax.swing.JTextArea();
        messageInputField = new javax.swing.JTextField();
        sendButton = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taMessageDisplay.setColumns(20);
        taMessageDisplay.setRows(5);
        taMessageDisplay.setEnabled(false);
        jScrollPane1.setViewportView(taMessageDisplay);

        sendButton.setLabel("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        sendCurrentText();
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }

        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageInputField;
    private java.awt.Button sendButton;
    private javax.swing.JTextArea taMessageDisplay;
    // End of variables declaration//GEN-END:variables
}
